--------------------------------------------------------
--  File created - Tuesday-July-14-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BITS_PROBLEMS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BITS_PROBLEMS" 
   (	"SERIAL" VARCHAR2(20 BYTE), 
	"PROBLEM" VARCHAR2(1000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BITS_PROBLEMS
SET DEFINE OFF;
Insert into SYSTEM.BITS_PROBLEMS (SERIAL,PROBLEM) values ('1','THIS IS PROBLEM 1');
Insert into SYSTEM.BITS_PROBLEMS (SERIAL,PROBLEM) values ('2','THIS IS PROBLEM 2');
Insert into SYSTEM.BITS_PROBLEMS (SERIAL,PROBLEM) values ('3','THIS IS PROBLEM 3');
Insert into SYSTEM.BITS_PROBLEMS (SERIAL,PROBLEM) values ('4','THIS IS PROBLEM 4');
Insert into SYSTEM.BITS_PROBLEMS (SERIAL,PROBLEM) values ('5','THIS IS PROBLEM 5');
--------------------------------------------------------
--  DDL for Index BITS_PROBLEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BITS_PROBLEMS_PK" ON "SYSTEM"."BITS_PROBLEMS" ("SERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BITS_PROBLEMS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BITS_PROBLEMS" ADD CONSTRAINT "BITS_PROBLEMS_PK" PRIMARY KEY ("SERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."BITS_PROBLEMS" MODIFY ("PROBLEM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BITS_PROBLEMS" MODIFY ("SERIAL" NOT NULL ENABLE);
