--------------------------------------------------------
--  File created - Tuesday-July-14-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BITS_USER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BITS_USER" 
   (	"USER_ID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"CONTACT" VARCHAR2(200 BYTE), 
	"TEAMNAME" VARCHAR2(200 BYTE), 
	"COLLEGE" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BITS_TEAM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BITS_TEAM" 
   (	"TEAMNAME" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"STARTTIME" VARCHAR2(200 BYTE), 
	"SCORE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.BITS_USER
SET DEFINE OFF;
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (10,'a','s','s','dssdads','s');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (8,'v','v','v','dfdfs','v');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (9,'v2','v2','v2','dfdfs332','2v');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (11,'d','d','d','dcdsc ds','d');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (12,'f','f','f','1234','f');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (13,'1','1','1','hkjvkhgv','1');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (14,'2','2','2','hkjvkhgv','2');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (21,'vaibhav','1','1','teamzaw','1');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (22,'vaibhav1','1','1','teamx','1');
Insert into SYSTEM.BITS_USER (USER_ID,NAME,EMAIL,CONTACT,TEAMNAME,COLLEGE) values (23,'vaibhav 2','2','2','teamx','2');
REM INSERTING into SYSTEM.BITS_TEAM
SET DEFINE OFF;
Insert into SYSTEM.BITS_TEAM (TEAMNAME,PASSWORD,STARTTIME,SCORE) values ('xyz','xyz','02:17:50',10);
Insert into SYSTEM.BITS_TEAM (TEAMNAME,PASSWORD,STARTTIME,SCORE) values ('abc','abc','02:37:55',10);
Insert into SYSTEM.BITS_TEAM (TEAMNAME,PASSWORD,STARTTIME,SCORE) values ('TestTeam1','0.18754480245234229','0',0);
Insert into SYSTEM.BITS_TEAM (TEAMNAME,PASSWORD,STARTTIME,SCORE) values ('teamzaw','0.3931148628966322','02:27:20',0);
Insert into SYSTEM.BITS_TEAM (TEAMNAME,PASSWORD,STARTTIME,SCORE) values ('teamx','0.08593382745511435','0',0);
--------------------------------------------------------
--  DDL for Index BITS_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BITS_USER_PK" ON "SYSTEM"."BITS_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BITS_TEAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."BITS_TEAM_PK" ON "SYSTEM"."BITS_TEAM" ("TEAMNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BITS_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BITS_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BITS_USER" ADD CONSTRAINT "BITS_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BITS_TEAM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BITS_TEAM" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BITS_TEAM" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BITS_TEAM" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BITS_TEAM" ADD CONSTRAINT "BITS_TEAM_PK" PRIMARY KEY ("TEAMNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger BITS_USER_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."BITS_USER_TRG" BEFORE INSERT ON BITS_USER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.USER_ID IS NULL THEN
      SELECT BITS_USER_SEQ.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."BITS_USER_TRG" ENABLE;
