/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiler;

/**
 *
 * @author Rahul
 */
public class BitsInterface extends javax.swing.JFrame {

    session S;
    
    
    public BitsInterface(session S) {
        initComponents();
        this.S = S;
        setProblems();
        

    }

    private void setProblems(){
        problemStatementTextArea.setText(S.getProblem(1));
    problemStatementTextArea1.setText(S.getProblem(2));
    problemStatementTextArea2.setText(S.getProblem(3));
    problemStatementTextArea3.setText(S.getProblem(4));
    problemStatementTextArea4.setText(S.getProblem(5));
        
    }
  
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        rankButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        teamNameLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        problemStatementPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        problemStatementTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        problemStatementPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        problemStatementTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        problemStatementPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        problemStatementTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        problemStatementPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        problemStatementTextArea3 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        problemStatementPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        problemStatementTextArea4 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        basePanel.setLayout(null);

        rankButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        rankButton.setForeground(new java.awt.Color(255, 255, 255));
        rankButton.setText("Rank");
        rankButton.setBorder(null);
        rankButton.setContentAreaFilled(false);
        rankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankButtonActionPerformed(evt);
            }
        });
        basePanel.add(rankButton);
        rankButton.setBounds(78, 548, 154, 29);

        refreshButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.setContentAreaFilled(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        basePanel.add(refreshButton);
        refreshButton.setBounds(78, 600, 154, 29);

        teamNameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        teamNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(teamNameLabel);
        teamNameLabel.setBounds(50, 130, 210, 50);

        timerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(timerLabel);
        timerLabel.setBounds(50, 195, 210, 50);

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basePanel.add(statusLabel);
        statusLabel.setBounds(62, 270, 187, 229);

        problemStatementPanel.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea.setColumns(20);
        problemStatementTextArea.setRows(5);
        jScrollPane1.setViewportView(problemStatementTextArea);

        javax.swing.GroupLayout problemStatementPanelLayout = new javax.swing.GroupLayout(problemStatementPanel);
        problemStatementPanel.setLayout(problemStatementPanelLayout);
        problemStatementPanelLayout.setHorizontalGroup(
            problemStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanelLayout.setVerticalGroup(
            problemStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel);
        problemStatementPanel.setBounds(387, 90, 820, 100);

        jButton1.setText("...");
        basePanel.add(jButton1);
        jButton1.setBounds(1233, 235, 40, 40);

        problemStatementPanel1.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea1.setColumns(20);
        problemStatementTextArea1.setRows(5);
        jScrollPane2.setViewportView(problemStatementTextArea1);

        javax.swing.GroupLayout problemStatementPanel1Layout = new javax.swing.GroupLayout(problemStatementPanel1);
        problemStatementPanel1.setLayout(problemStatementPanel1Layout);
        problemStatementPanel1Layout.setHorizontalGroup(
            problemStatementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel1Layout.setVerticalGroup(
            problemStatementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel1);
        problemStatementPanel1.setBounds(387, 204, 820, 100);

        jButton2.setText("...");
        basePanel.add(jButton2);
        jButton2.setBounds(1233, 346, 40, 40);

        problemStatementPanel2.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea2.setColumns(20);
        problemStatementTextArea2.setRows(5);
        jScrollPane3.setViewportView(problemStatementTextArea2);

        javax.swing.GroupLayout problemStatementPanel2Layout = new javax.swing.GroupLayout(problemStatementPanel2);
        problemStatementPanel2.setLayout(problemStatementPanel2Layout);
        problemStatementPanel2Layout.setHorizontalGroup(
            problemStatementPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel2Layout.setVerticalGroup(
            problemStatementPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel2);
        problemStatementPanel2.setBounds(387, 318, 820, 100);

        jButton3.setText("...");
        basePanel.add(jButton3);
        jButton3.setBounds(1233, 460, 40, 40);

        problemStatementPanel3.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea3.setColumns(20);
        problemStatementTextArea3.setRows(5);
        jScrollPane4.setViewportView(problemStatementTextArea3);

        javax.swing.GroupLayout problemStatementPanel3Layout = new javax.swing.GroupLayout(problemStatementPanel3);
        problemStatementPanel3.setLayout(problemStatementPanel3Layout);
        problemStatementPanel3Layout.setHorizontalGroup(
            problemStatementPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel3Layout.setVerticalGroup(
            problemStatementPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel3);
        problemStatementPanel3.setBounds(387, 432, 820, 100);

        jButton4.setText("...");
        basePanel.add(jButton4);
        jButton4.setBounds(1233, 577, 40, 40);

        problemStatementPanel4.setBackground(new java.awt.Color(255, 255, 255));

        problemStatementTextArea4.setColumns(20);
        problemStatementTextArea4.setRows(5);
        jScrollPane5.setViewportView(problemStatementTextArea4);

        javax.swing.GroupLayout problemStatementPanel4Layout = new javax.swing.GroupLayout(problemStatementPanel4);
        problemStatementPanel4.setLayout(problemStatementPanel4Layout);
        problemStatementPanel4Layout.setHorizontalGroup(
            problemStatementPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        problemStatementPanel4Layout.setVerticalGroup(
            problemStatementPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        basePanel.add(problemStatementPanel4);
        problemStatementPanel4.setBounds(387, 546, 820, 100);

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        basePanel.add(jButton5);
        jButton5.setBounds(1233, 120, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiler/images/Home Screen.jpg"))); // NOI18N
        basePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 700);

        optionsMenu.setText("Options");
        jMenuBar1.add(optionsMenu);

        exitMenu.setText("Exit");
        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BitsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BitsInterface(new session("","")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JPanel problemStatementPanel;
    private javax.swing.JPanel problemStatementPanel1;
    private javax.swing.JPanel problemStatementPanel2;
    private javax.swing.JPanel problemStatementPanel3;
    private javax.swing.JPanel problemStatementPanel4;
    private javax.swing.JTextArea problemStatementTextArea;
    private javax.swing.JTextArea problemStatementTextArea1;
    private javax.swing.JTextArea problemStatementTextArea2;
    private javax.swing.JTextArea problemStatementTextArea3;
    private javax.swing.JTextArea problemStatementTextArea4;
    private javax.swing.JButton rankButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
