/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiler;

/**
 *
 * @author Home
 */
public class Problem extends javax.swing.JFrame {

    /**
     * Creates new form Problem
     */
    public Problem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        RankButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        teamNameLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        LanguageMenu = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        problemStatementScrollPane = new javax.swing.JScrollPane();
        problemStatement = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        codeTextAea = new javax.swing.JTextArea();
        FileName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1364, 703));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        homeButton.setAutoscrolls(true);
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(98, 60, 52, 52);

        RefreshButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 255, 255));
        RefreshButton.setText("Refresh");
        RefreshButton.setBorder(null);
        RefreshButton.setContentAreaFilled(false);
        RefreshButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton);
        RefreshButton.setBounds(48, 598, 155, 30);

        RankButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        RankButton.setForeground(new java.awt.Color(255, 255, 255));
        RankButton.setText("Rank");
        RankButton.setBorder(null);
        RankButton.setBorderPainted(false);
        RankButton.setContentAreaFilled(false);
        RankButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RankButton);
        RankButton.setBounds(48, 547, 155, 30);

        StatusLabel.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(StatusLabel);
        StatusLabel.setBounds(32, 271, 187, 228);

        teamNameLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        teamNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(teamNameLabel);
        teamNameLabel.setBounds(20, 120, 210, 50);

        timerLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(timerLabel);
        timerLabel.setBounds(20, 185, 210, 50);

        SaveButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setBorder(null);
        SaveButton.setBorderPainted(false);
        SaveButton.setContentAreaFilled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton);
        SaveButton.setBounds(340, 613, 155, 30);

        SubmitButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton.setText("Submit");
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton);
        SubmitButton.setBounds(1088, 614, 155, 29);

        uploadButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        uploadButton.setForeground(new java.awt.Color(255, 255, 255));
        uploadButton.setText("Upload");
        uploadButton.setContentAreaFilled(false);
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadButton);
        uploadButton.setBounds(1088, 431, 155, 30);

        LanguageMenu.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        LanguageMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C", "C++", "C#", "Python", "Python 3", "Java", "Java 8", "PHP", "Perl", "Ruby", "Objective-C", "Haskell", "Clojure", "Scala", "Common Lisp (SBCL)", "Lua", "Erlang", "Javascript", "Go", "Brainf**k", "Groovy", "OCaml", "F#", "VB.NET", "LOLCODE", "Smalltalk", "Tcl", "R", "GNU Octave", "COBOL", "RACKET", "RUST", "SWIFT", "PASCAL", "BASH", "D" }));
        LanguageMenu.setBorder(null);
        LanguageMenu.setOpaque(false);
        jPanel1.add(LanguageMenu);
        LanguageMenu.setBounds(827, 618, 150, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        problemStatement.setColumns(20);
        problemStatement.setRows(5);
        problemStatementScrollPane.setViewportView(problemStatement);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(problemStatementScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(problemStatementScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(340, 80, 940, 320);

        codeTextAea.setColumns(20);
        codeTextAea.setRows(500);
        codeTextAea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(codeTextAea);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 450, 661, 143);

        FileName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(FileName);
        FileName.setBounds(940, 530, 360, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiler/images/Problem Statement.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-30, 0, 1390, 700);

        jMenu1.setText("Options");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RankButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FileName;
    private javax.swing.JComboBox LanguageMenu;
    private javax.swing.JButton RankButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextArea codeTextAea;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea problemStatement;
    private javax.swing.JScrollPane problemStatementScrollPane;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
