/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiler;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author vAibHav
 */
public class startScreen extends javax.swing.JFrame {
     session S;//Session that is passed from one screen to another
    
     
    /**
     * Creates new form startScreen
     */
    public startScreen(session ssn) {
        S = ssn;
        initComponents();
        
    }
    
    public startScreen(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1366, 728));

        jPanel1.setPreferredSize(new java.awt.Dimension(1364, 703));
        jPanel1.setLayout(null);

        startButton.setFont(new java.awt.Font("Tekton Pro", 0, 20)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Start");
        startButton.setContentAreaFilled(false);
        startButton.setFocusable(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);
        startButton.setBounds(600, 560, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compiler/images/inst_screen.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1364, 703);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Start Button Clicked");
        try {
            //Checking the session
            if(S == null)
            {    
                System.out.println("Session not created!");
                JOptionPane.showMessageDialog(null, "Session could not be created.");
                return;
            }
            
            //Connection con= S.getConnection();
             setTime();
        }catch (Exception ex) {
            System.out.println(ex);
        }
               
    }//GEN-LAST:event_startButtonActionPerformed
    
     public void setTime()
    {
      try{
         Calendar cal = Calendar.getInstance();
         
         SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
       //System.out.println((sdf.format(cal.getTime())));
         String Time = sdf.format(cal.getTime());
         Connection c= S.getConnection();
         String TName = S.getUsername();
        //System.out.println(TName);
         
         String checkStarttime= "SELECT * FROM system.Bits_team where teamname=?";
         PreparedStatement stm = c.prepareStatement(checkStarttime);
         stm.setString(1, TName);
         ResultSet res = stm.executeQuery();
         res.next();
         String starttime = res.getString("starttime");
         if(starttime.equalsIgnoreCase("0")){
             
             String addTime= "UPDATE system.Bits_team SET starttime =? where teamname=?";
       
             PreparedStatement stm1 = c.prepareStatement(addTime);
             stm1.setString(1, Time);
             stm1.setString(2, TName);
             stm1.executeQuery();
             //closing the statement
             stm1.close();
             
         }
         BitsInterface bts = new BitsInterface(S);
         bts.setLocation(0, 0);
         bts.setVisible(true);
         setVisible(false);
         
      }catch (SQLException ex) {
          System.out.println("SQL Exception!");
          System.out.print(ex);
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*session S = new session("xyz","xyz");
        Connection con =S.makeConnection();
        S.updateCon(con);
        System.out.println(S.getConnection());
        startScreen ss =new startScreen(S);*/
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
